### ISSUE TITLE
Crash on launching in Nexus 5x

### ISSUE THREAD

**Issue by ragsagar** [zulip/zulip-android#103] opened 2016-07-26 11:56 UTC
I installed zulip app from play store in my Nexus 5x with Android version 6.0.1. Whenever I try to launch the app, it is crashing immediately . Attaching the log I caught from Android Monitor in Android Studio.

[zulip_android_crash.txt](https://github.com/zulip/zulip-android/files/383725/zulip_android_crash.txt)

**Comment by timabbott** [comment] 2016-07-26 18:17
I think this is a duplicate of #6, the fix to which sadly hasn't made it into the Android play store yet...

**Closed by timabbott** 2016-07-26 18:17 UTC
Labels: duplicate

**Comment by brainwane** [comment] 2016-07-26 18:20
@ragsagar thanks for reporting it!
