### ISSUE TITLE
Cannot close the chatbox 

### ISSUE THREAD

**Issue by minervapanda** [zulip/zulip-android#192] opened 2016-10-03 03:54 UTC
Once chatbox is opened then , we need to close and re-open the app to close the chatbox.

**Comment by timabbott** [comment] 2016-10-03 03:59
Thanks for the report @minervapanda!  You can close it by swiping it to the side, but I agree that the current situation is super annoying.  

See https://github.com/zulip/zulip-android/issues/178 and https://github.com/zulip/zulip-android/issues/171 for some concrete proposals for how to improve this (I'm closing this issue as a duplicate of those two issues).

**Closed by timabbott** 2016-10-03 03:59 UTC
Labels: duplicate
