### ISSUE TITLE
Best Network Library suited for Android Project

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#29] opened 2016-03-20 21:46 UTC
As I and @timabbott had a conversation for the best network library suited for the project I did some test's for 4 libraries which are HttpURLConnection, Retrofit, Volley and the current Apache Client.

I did these test on a 1.5 Mbps internet connection to fetch from the server having custom headers for authorization and record the time taken in millisecond. Total size to fetch was **487 Kb** 

So I conducted 5 test's with each of the libraries and got the following results- 

|   Name   | HTTPURLConnection | RetroFit | Apache Client | Volley |
|:--------:|:-----------------:|:--------:|:-------------:|:------:|
|          |                   |          |               |        |
| 1st Test |        3172       |   2886   |      3255     |  3127  |
| 2nd Test |        3157       |   2776   |      3275     |  3055  |
| 3rd Test |        3121       |   2835   |      3292     |  3082  |
| 4th Test |        3195       |   2859   |      3223     |  3145  |
| 5th Test |        3175       |   2801   |      3283     |  3048  |

Therefore I found the average values - 

|        Name       | Average Time Taken (ms) | Minimal Lines of Code |
|:-----------------:|:-----------------------:|:---------------------:|
| HTTPURLConnection |           3164          |           28          |
|      Retrofit     |           2831          |           9           |
|   Apache Client   |           3265          |           24          |
|       Volley      |           3091          |           25          |

I have also uploaded the [project test's](https://github.com/kunall17/zulip-network-tests) I built for these libaries
Now by seeing the result we observe Retrofit is the best in these libraries in terms of speed, total code.
What are your suggestions for replacing the current library?

**Comment by timabbott** [comment] 2016-03-21 00:30
Cool, yeah, that seems like reasonably compelling evidence that Retrofit is faster (at least on your test network) and less code.

**Comment by ryansnowboarder** [comment] 2016-03-23 03:32
Hmm... interesting! 487 Kb sounds reasonable for what that app would normally fetch upon startup. The REAL question: is that time difference actually a significant contribution to speeding up the app startup? I'm sure there's some other things going on that might slow things down...

**Comment by ryansnowboarder** [comment] 2016-03-23 03:37
Would you happen to have a speed test screen capture for that internet connection? I'm curious as to what the latency of the connection was - not that it's a likely issue we're all being sent through a proxy on a satellite, but might as well cover all the bases.

**Comment by kunall17** [comment] 2016-03-23 11:14
@ryansnowboarder Yeah definitely, I did these tests in night time so i'll send you the latency test's in night as the speeds in my hostel vary significantly in day and night (less number of users in night).

**Comment by ryansnowboarder** [comment] 2016-03-23 21:28
@kunall17 - thanks! Another thought (sorry to poke holes in your test, but those results are very strange to me now I think about it and I would be more worried if your test turns out to be solid): 

You said: "I did these test on a 1.5 Mbps internet connection to fetch from the server." 

 So, clearly we're not downloading at anything close to an average of 1.5 Mbps if it taking 2800+ ms to fetch 487 Kb. Where on the internet was the server relative to the app you ran? Is this the same path through the internet as the two points you tested in the speed test? Same competition for bandwidth too? What's the most data your server can throw down the pipe? 

If you didn't use an isolated system with no connection to the outside internet of everything else and with the same competition for bandwidth, then there's a good chance any testing between two points on the internet will not take the same path with the same competition for bandwidth and any data gathered is essentially non-reproducible and unpredictable. For example, let's say you were in your hostel and you tested each network library sequentially - 5 times for HTTPURLConnection, then 5 times for Retrofit, and so on. Your server is located somewhere nearby on a public WIFI network supported by two different antennas. If someone else on the network suddenly decides to download a dank meme or rare pepe during your testing, then all sorts of strange things can happen! Oh look, a rare pepe! 

![rare_pepe](https://cloud.githubusercontent.com/assets/6963222/14001460/5a2f6706-f11c-11e5-9ab6-514a8acc7b68.png)

 Lastly, is there too much handshaking between the client and server before the download starts? 

Thoughts @timabbott?

**Comment by niftynei** [comment] 2016-03-24 09:10
This is unsolicited and shouldn't impact your speed.tests and I apologize in advance for the pedantry, but it's worth pointing out that Retrofit itself isn't a.networking library -- it's a wrapper for network call object marshalling.

The networking library that backs Retrofit is OkHttp. Since it appears you're using the speed test as a proxy for picking the best library, it may be worthwhile to mention that OkHttp has officially replaced the Apache networking stack as the default/package Android networking library.

As an unverified aside, I believe that Volley uses one of the Apache network stacks but it's been a few years since I've used it -- it's possible that they've also switched to OkHttp.

It occurs to me that one of the explanations for the difference in timings btw the libraries may be not necessarily the network call but instead your json to POJO marshalling code. I haven't looked at.your test code so please disregard this if you've already accounted for that.

Excited to get a new version of zulip soon! :)

**Comment by ryansnowboarder** [comment] 2016-03-24 19:48
"It occurs to me that one of the explanations for the difference in timings
btw the libraries may be not necessarily the network call but instead your
json to POJO marshalling code. I haven't looked at.your test code so please
disregard this if you've already accounted for that."

Yes, absolutely! There's tons of different things going on and transferring
data over the net is just one of them.

**Comment by kunall17** [comment] 2016-03-26 12:04
@niftynei thank you for the information you gave. I am aware of the fact that there are many more factors than speed, well it was a starting step for searching the right library, I will test using the OkHttp as well very soon.
Currently I have not done the parsing of the JSON just downloaded the JSON, will test them as well. 

@ryansnowboarder "**If someone else on the network suddenly decides to download a dank meme or rare pepe during your testing, then all sorts of strange things can happen! **"
The network does not differ that much, I just meant it differs from night and day!

It would be great if you guys could suggest some more test's to determine the best library? 
Or any other library which you think would be good enough?

**Comment by niftynei** [comment] 2016-03-26 15:44
Retrofit lets you pick both your networking library and the JSON / data converter so you could make those decisions independently of whether to use Retrofit or not. 

Retrofit has one of the more concise APIs for making network calls & it works well with RxJava, if that's a consideration.

I'm not sure I understand the motivation for testing the library tbh. OkHttp vs Apache is a good test. GSON vs Jackson vs ?? -- also probably a good test. Pretty sure the GSON vs Jackson has already been done.

**Comment by niftynei** [comment] 2016-07-12 13:53
Converted to OKHttp with #69 . 🎉

**Closed by niftynei** 2016-07-12 13:53 UTC
