### ISSUE TITLE
Notification support

### ISSUE THREAD

**Issue by pkaske** [zulip/zulip-android#112] opened 2016-08-01 08:29 UTC
It seems there is no way to have notifications when new messages arrive. Am I overlooking something?

**Comment by timabbott** [comment] 2016-08-02 00:11
The Android app supports push notifications, but I think there may be some tooling complexities with doing this against your own server.  I've been meaning to try to find time to look into how this works.  @kunall17 @niftynei is your understanding that GCM is tied to the Google Auth tangle of issues around having a single app that can talk to multiple servers run by different parties?

**Comment by kunall17** [comment] 2016-08-02 04:14
Yeah the current google ID is also hardcoded https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/gcm/Notifications.java#L25 in the application, well I tried to debug if the dev server is sending GCM messages I never get these logging error or info here  [L185](https://github.com/zulip/zulip/blob/0aae0eab497f7a770fa8f17b32fc471405f6228e/zerver/lib/push_notifications.py#L185) or [L195](https://github.com/zulip/zulip/blob/0aae0eab497f7a770fa8f17b32fc471405f6228e/zerver/lib/push_notifications.py#L195) or any other GCM debug! 

But why do we need GCM, we get the new messages via the AsycGetEvents queue?

**Comment by kunall17** [comment] 2016-08-02 04:47
EDIT: GCM should be used, now got it! 

I'll post a PR to fetch the google client ID and register from that ID.

**Comment by niftynei** [comment] 2016-08-02 15:02
afaict GCM has been working great, both on dev and prod builds.

**Comment by kunall17** [comment] 2016-08-04 19:49
@timabbott have you checked if the GCM is sending messages from the server side?

**Comment by timabbott** [comment] 2016-08-04 19:51
Well for zulip.tabbott.net we currently get this server error logged, so maybe that server needs some configuration done.
`Attempting to send a GCM push notification, but no API key was configured`


@kunall17 what does one need to do to enable GCM on the server side with our current setup?  (We should add how to do that to our documentation, possibly for both the server and the app, but I guess we should start with my setting it up for zulip.tabbott.net)

**Comment by pkaske** [comment] 2016-08-04 19:58
Doc on that would be awesome!

**Comment by kunall17** [comment] 2016-08-04 20:07
@timabbott I changed the ID in the android project and tried to register a GCM in the server, can you check?

I'll add docs once we get this working!

**Comment by timabbott** [comment] 2016-08-04 22:09
There's exactly one such GCM warning in the logs from today; :
`2016-08-04 15:51:32,528 ERROR    Attempting to send a GCM push notification, but no API key was configured`
The current time in that log file is `18:07:18,351` (aka US Eastern time), and your comment @kunall17 was thus at `16:07` in that timezone, which means it's possible that comes from your testing and possibly not... we can probably verify a future attempt if you e.g. do it twice and record the time precisely.

**Comment by kunall17** [comment] 2016-08-06 21:02
@timabbott sorry for the late reply! 

So I used #114 for doing this, 
I registered a GCM ID in your server
```
08-07 02:26:07.732 16628-17935/com.zulip.android.dev I/GCM: Device registered, registration ID=APA91bFPW3Rt1WB4f2bruG-Qol6Zqep6kfrn8XaLerX8KZYWda2BYfCplT5VfsyUBrJZ9jac4UoqsoyvouHjd1zjY7PxWJD_rQcpsWIq210UY1v0j2q6yNkDjU5L-Lb3tHD477tX27-O
08-07 02:26:07.737 16628-17935/com.zulip.android.dev I/OkHTTP.request: POST https://zulip.tabbott.net/api/v1/users/me/android_gcm_reg_id
```

This time is according to IST (Indian Standard TIme) so according to EST it should be 5:01 PM, Saturday, 6 August 2016

**Comment by timabbott** [comment] 2016-08-08 22:38
I didn't get such a logged error around that time (there's just one new one on 8/5).  However, on reading the error message, it's clear the problem here is that zulip.tabbott.net doesn't have a registered GCM API key in the `ANDROID_GCM_API_KEY` setting.  @kunall17 are there any special instructions for registering that?

**Comment by timabbott** [comment] 2016-08-08 22:51
OK I created a GCM key for zulip.tabbott.net.  Now the the GCM-related error message I see in the logs is this:

`GCM: Delivery to <giant key ID> failed: MismatchSenderId`

I think the problem now is that the app is configured with the SENDER_ID for zulip.com hardcoded:
```
$ git grep SENDER_ID
app/src/main/java/com/zulip/android/gcm/Notifications.java:    private static final String SENDER_ID = "835904834568";
app/src/main/java/com/zulip/android/gcm/Notifications.java:                            regid = gcm.register(SENDER_ID);
```

which is exactly what #114 fixes; so we should test again once with that version.

**Comment by timabbott** [comment] 2016-08-08 23:09
(So it's possible that your branch will work now @kunall17)

**Comment by kunall17** [comment] 2016-08-10 17:56
@timabbott
`registered again 08-10 23:20:12.990 12626-12626/com.zulip.android.dev I/GCM: Already registered for GCM: `

Can you please verify if messages are being sent?

**Comment by timabbott** [comment] 2016-08-10 22:03
Just to update this thread, I think we've determined that GCM does not support having multiple Google accounts associated with the same Android app in the Play Store.  We're actively discussing options with some folks at Google, but it's very possible we'll end up needing to do something like https://github.com/mattermost/push-proxy to make GCM work with more than one server:

**Comment by timabbott** [comment] 2016-09-10 17:34
This is primarily a server-side issue, we need to do: https://github.com/zulip/zulip/issues/1767

**Comment by kunall17** [comment] 2016-12-28 18:38
@Sam1301 @vishwesh3 @saketkumar95 It would be awesome if any of you guys could work on this issue?
I'll explain it once again, so the problem with GCM push notifications, the GCM library doesn't support multiple

**Comment by saketkumar95** [comment] 2016-12-28 18:43
@kunall17 I will work on this. :)

**Comment by kunall17** [comment] 2016-12-28 18:43
@Sam1301 @vishwesh3 @saketkumar95 It would be awesome if any of you guys could work on this issue?
The app feels incomplete without providing notifications! 
I'll explain it once again, so the problem is we cannot have multiple servers with different ANDROID_GCM_API_KEY linked to our Android project! 
So to support this as timabbott stated in the comment above we need to modify the python server to use some kind off different push notifications support (https://github.com/mattermost/push-proxy) and make it work on our Android app! 
So this would require you to edit the server as well! 
This is an important feature which is left out and making the app incomplete! 
@timabbott can you please mark this as high priority?

**Comment by vishwesh3** [comment] 2016-12-28 19:48
@kunall17 I would like to work on this

**Comment by saketkumar95** [comment] 2016-12-28 20:14
@vishwesh3 Working on this.

**Comment by Sam1301** [comment] 2016-12-28 23:40
@saketkumar95 feel free to reach me out in case of any help or discussion on this issue.

**Comment by timabbott** [comment] 2016-12-28 23:41
I'm also happy to help provide advice on how to get this server-side backend implementation finished.

**Comment by saketkumar95** [comment] 2016-12-29 01:31
@timabbott @Sam1301 I would really love to take help from you all. A big task for me to do. :)

**Comment by saketkumar95** [comment] 2016-12-29 18:18
I will be working on this from first week of january. Currently completing all my pending assigned issues. :)

**Comment by timabbott** [comment] 2017-01-04 05:22
See https://github.com/zulip/zulip/pull/3092 for the current partial implementation (I just rebased @niftynei's work to be usable on top of master).

**Comment by kunall17** [comment] 2017-01-07 20:52
@saketkumar95 any progress in the notification support?

**Comment by saketkumar95** [comment] 2017-01-08 04:20
@kunall17 Yes. Currently trying to understand the backend. Reference https://github.com/zulip/zulip/pull/3124

**Comment by kunall17** [comment] 2017-01-15 18:42
@saketkumar95 Any updates?

**Comment by saketkumar95** [comment] 2017-01-15 19:25
@kunall17 I was little bit busy from 1 week in travelling. Didn't gave much time on this. Currently i'm learning about this server side backends only. I really need some experts help to resolve this.

**Comment by kunall17** [comment] 2017-01-19 04:28
@saketkumar95 Yeah, so please work on this PR only, and do ask anything at the zulip.tabbott.net will be happy to help! :)

**Comment by OliverEvans96** [comment] 2017-01-28 03:09
I wonder if, in the mean time, we could implement push notifications via the web app. I noticed the other day that after I signed into Facebook on my android from Chrome, I started getting push notifications, even though I don't have the facebook so installed. Here's the Google developer page : https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/

**Comment by OliverEvans96** [comment] 2017-01-28 03:10
It seems like web notifications could be a way to circumvent the one server per app restriction.

**Comment by timabbott** [comment] 2017-05-16 19:35
The server-side work for this was completed just now, and will be in Zulip 1.6.  I'm going to write up some documentation for how it needs to be setup and post it here soon.

**Comment by timabbott** [comment] 2017-05-16 19:36
(No client-side changes are needed other than possibly a logout+login, so closing this).

@kunall17 @vishwesh3 can one of you investigate whether one needs to logout and then login again to cause the app to register for GCM, or whether that happens automatically whenever the app is opened?  We'll want to include that detail in the documentation.

**Closed** 2017-05-16 20:39 UTC
Labels: high-priority
