### ISSUE TITLE
Camera app crashing after choosing to upload the image clicked. 

### ISSUE THREAD

**Issue by sashafierce** [zulip/zulip-android#306] opened 2017-01-17 21:14 UTC
This occurred while testing image upload via phone's default camera app ( phone having API level 19) , after pressing the 'tick' OK button the camera app crashes.

<img src=https://cloud.githubusercontent.com/assets/18103181/22039162/33ab1702-dd24-11e6-9db1-58c353bd6dca.png width=300 height=500 />

Secondly , choosing to cancel upload of the image clicked or pressing back button in camera app does not lead to the activity which originally launched the camera intent instead directs to ZulipActivity.

**Comment by timabbott** [comment] 2017-01-17 21:20
@sashafierce can you get the traceback?

@Sam1301 any idea what the issue is here?

**Comment by Sam1301** [comment] 2017-01-17 21:41
@sashafierce this seems to be an issue only on lower api levels. I just tested it on api level 23 but couldn't reproduce the error... Investigating more

**Comment by timabbott** [comment] 2017-01-17 21:54
Cool.  In general we want to support down to api level 16.

**Comment by Sam1301** [comment] 2017-01-18 00:23
Thanks a lot @sashafierce for reporting this bug :+1:  I have solved this issue using  #308. I could only test it on an emulator. Can you please try this solution on your device and let me know if this works?

**Comment by sashafierce** [comment] 2017-01-18 14:27
Okay now its not crashing but still I am unable to upload the image , the captured image is not shown in the ImageView and when I choose the 'tick' OK button it returns back to camera intent instead of uploading.

**Comment by Sam1301** [comment] 2017-01-18 17:31
hmm... I didn't get this error in emulator running on api 19, the image was shown in imageview, weird :/ Can you give me a stacktrace (if there was one, after choosing 'tick')? Thanks!

**Comment by kunall17** [comment] 2017-01-28 04:02
@sashafierce can you post the stacktrace for this one?

**Comment by yadav-rahul** [comment] 2017-01-28 06:38
@kunall17 I am also facing similar issue in Android version `4.1.2`.

![rsz_screenshot_2017-01-28-11-56-55](https://cloud.githubusercontent.com/assets/15157620/22394866/08762fbe-e552-11e6-8448-2f938e414efc.png)

Here is the stack trace for this:

`01-28 11:56:34.952 24364-24364/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{4263c6c0 24364:com.sec.android.app.camera/u0a70} (pid=24364, uid=10070) that is not exported from uid 10131
                                                       at android.os.Parcel.readException(Parcel.java:1425)
                                                       at android.os.Parcel.readException(Parcel.java:1379)
                                                       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2574)
                                                       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4358)
                                                       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:1825)
                                                       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1107)
                                                       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:622)
                                                       at android.content.ContentResolver.openOutputStream(ContentResolver.java:495)
                                                       at android.content.ContentResolver.openOutputStream(ContentResolver.java:471)
                                                       at com.sec.android.app.camera.Camera$LastContentUriCallback.onCompleted(Camera.java:5863)
                                                       at com.sec.android.app.camera.Camera.onLaunchGallery(Camera.java:5738)
                                                       at com.sec.android.app.camera.Camera.onImageStoringCompleted(Camera.java:5232)
                                                       at com.sec.android.app.camera.CameraEngine.imageStoringCompleted(CameraEngine.java:2309)
                                                       at com.sec.android.app.camera.CeStateInitialized.handleMessage(CeStateInitialized.java:47)
                                                       at com.sec.android.app.camera.CameraEngine$StateMessageHandler.handleMessage(CameraEngine.java:250)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4960)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                       at dalvik.system.NativeStart.main(Native Method)`

**Comment by Sam1301** [comment] 2017-01-28 06:40
@yadav-rahul yes, the crash I think is fixed in #308 pr. Can you please try that pr's solution and let me know in case its fixed? Thanks :)

**Comment by yadav-rahul** [comment] 2017-01-28 07:04
@Sam1301 OK. I am testing #308.

**Closed** 2017-01-28 18:01 UTC
Labels: bug, help wanted
