### ISSUE TITLE
Disconnected handler for queue 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#121] opened 2016-08-12 05:45 UTC
I'm not sure if this is an error in the server side or the android client and no other mobiles/web was connected to the server at this time!
I encountered this after exiting App 2-3 times and starting again then i start recieving these logs

**Disconnected handler for queue 1470980116:0** 

Log of the server - 
```
2016-08-12 01:38:44,947 INFO     127.0.0.1       GET     200  30ms (lp: 12.3s) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:46,761 INFO     127.0.0.1       GET     200  15ms (lp: 791ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:46,763 INFO     127.0.0.1       GET     200  14ms /api/v1/event                                                                                                                s [1470980116:0/0] [was connected] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:47,834 INFO     127.0.0.1       GET     200  22ms (lp: 40ms) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:47,837 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:48,586 INFO     127.0.0.1       GET     200  20ms (lp: 767ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:49,664 INFO     127.0.0.1       GET     200  21ms (lp: 434ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:49,667 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:50,695 INFO     127.0.0.1       GET     200  23ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:50,697 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:51,729 INFO     127.0.0.1       GET     200  13ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:51,732 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:52,392 INFO     127.0.0.1       GET     200  12ms (lp: 671ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:52,396 INFO     127.0.0.1       POST    200  65ms (db: 4ms/2q)                                                                                                                 /api/v1/messages/flags [add read/37] actually 0 (iago@zulip.com via ZulipAndroid                                                                                                                )
2016-08-12 01:38:53,436 INFO     127.0.0.1       GET     200   7ms (lp: 669ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:53,438 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:54,176 INFO     127.0.0.1       GET     200  12ms (lp: 747ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:54,413 INFO     127.0.0.1       POST    200  71ms (db: 3ms/2q)                                                                                                                 /api/v1/messages/flags [add read/10] actually 0 (iago@zulip.com via ZulipAndroid                                                                                                                )
2016-08-12 01:38:54,465 INFO     127.0.0.1       GET     200  11ms /api/v1/event                                                                                                                s [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:55,499 INFO     127.0.0.1       GET     200  17ms (lp: 268ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:55,503 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:56,543 INFO     127.0.0.1       GET     200  13ms (lp: 1.1s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:56,546 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:57,574 INFO     127.0.0.1       GET     200  15ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:57,580 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)

```

@timabbott is this normal, or if error how to address this issue?

**Comment by timabbott** [comment] 2016-08-12 06:04
The server is (I think) behaving normally -- the `Disconnected handler` notices are just part of the normal logging for a get_events call where there's an event to return (though it's a little spammy).

Every response from the server has exactly 1 event being returned, so I suspect the problem is that the client is not correctly acknowledging the events that it is receiving from the server in the `GET /api/v1/events` calls by updating `last_event_id` in the next callback -- and as a result, it's making the same request over and over again.

**Comment by kunall17** [comment] 2016-08-12 06:18
I was trying to reproduce the issue but could not! 
Anyways, so the client should re register another queue ID when this is disconnected to solve this issue?

**Comment by timabbott** [comment] 2016-08-12 06:19
No, registering another queue would make the problem much worse.

The bug here is that the client is incorrectly failing the pass the correct `last_event_id` when connecting to the server -- we should review the logic for how the client updates `last_event_id` and make sure that it always increases it to the maximum of the event IDs it has received from the server.  My guess is we have a code path inside the event ID handler that returns early.

**Comment by timabbott** [comment] 2016-08-12 06:22
Looking at the code, one likely way for that sort of error to happen would be for `processEvents` to throw an exception -- that would skip the code that updates `last_event_id`.

**Comment by kunall17** [comment] 2016-08-20 10:22
I haven't got any `"Disconnected handler for queue"` message after this fix, this can be closed now!
If any one still get these logs please let me know!

**Comment by niftynei** [comment] 2016-08-22 18:25
Closing as fixed, we should reopen if the problem resurfaces.

**Closed by niftynei** 2016-08-22 18:25 UTC
